### PR TITLE
File System Update 

### PR DESCRIPTION
**Pull request by SangMLee**
Changed system for the analysis 
Added all required code for h2mu analysis

### CODE REVIEW

**Comment by jshlee** [comment]
why did you close?

**Comment by SangMLee** [comment]
Sorry there was a change that you told me to make that I didn’t do. Im going to re pull request right now though. I’ll just pull request the change after i’ve done it later( making the categories branches)
 

Sent from Mail for Windows 10

**Comment by jshlee** [comment]
remove .DS_Store files

**Comment by SangMLee** [comment]
I took it out, i think

**Pull request merged**
